# Generated by Django 5.0.7 on 2024-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
